[package]
name = "reddit2eink"
version = "0.0.1"
authors = ["Pablo Oliveira <pablo@sifflez.org>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
futures = "0.3"
roux = "1.1.1"
shell-words = "1.0.0"
tokio = { version = "0.2.22", features = ["full"] }
